default_title: Guitar Shed - Guitar Tabs | Backing Tracks | Lessons 

meta_keywords: "Guitar Tabs, Guitar Backing Tracks, Guitar Lessons, Guitar Pro Tabs, Guitar Videos"

meta_description: "Guitar Shed is an guitar learning web site dedicated to providing the best resources for learning to play the guitar.  Lessons, Guitar Tabs, Backing Tracks, and more."